export const RANKS = {
    ru: {
        Unknown: "Неизвестно",
        Bronze: "Бронза",
        Silver: "Серебро",
        Gold: "Золото",
        Platinum: "Платина",
        Diamond: "Алмаз",
        Master: "Мастер",
        Grandmaster: "Грандмастер",
        Challenger: "Претендент",
        Legend: "Легенда",
        Mythical: "Мифический"
    },
    en: {
        Unknown: "Unknown",
        Bronze: "Bronze",
        Silver: "Silver",
        Gold: "Gold",
        Platinum: "Platinum",
        Diamond: "Diamond",
        Master: "Master",
        Grandmaster: "Grandmaster",
        Challenger: "Challenger",
        Legend: "Legend",
        Mythical: "Mythical"
    },
    es: {
        Unknown: "Desconocido",
        Bronze: "Bronce",
        Silver: "Plata",
        Gold: "Oro",
        Platinum: "Platino",
        Diamond: "Diamante",
        Master: "Maestro",
        Grandmaster: "Gran Maestro",
        Challenger: "Retador",
        Legend: "Leyenda",
        Mythical: "Mítico"
    },
    fr: {
        Unknown: "Inconnu",
        Bronze: "Bronze",
        Silver: "Argent",
        Gold: "Or",
        Platinum: "Platine",
        Diamond: "Diamant",
        Master: "Maître",
        Grandmaster: "Grand Maître",
        Challenger: "Challenger",
        Legend: "Légende",
        Mythical: "Mythique"
    },
    ar: {
        Unknown: "غير معروف",
        Bronze: "برونزي",
        Silver: "فضي",
        Gold: "ذهبي",
        Platinum: "بلاتيني",
        Diamond: "ماسي",
        Master: "ماستر",
        Grandmaster: "جراند ماستر",
        Challenger: "متحدي",
        Legend: "أسطوري",
        Mythical: "خرافي"
    },
    hi: {
        Unknown: "अज्ञात",
        Bronze: "कांस्य",
        Silver: "रजत",
        Gold: "स्वर्ण",
        Platinum: "प्लैटिनम",
        Diamond: "हीरा",
        Master: "मास्टर",
        Grandmaster: "ग्रैंडमास्टर",
        Challenger: "चैलेंजर",
        Legend: "लीजेंड",
        Mythical: "पौराणिक"
    },
    bn: {
        Unknown: "অজানা",
        Bronze: "ব্রোঞ্জ",
        Silver: "সিলভার",
        Gold: "গোল্ড",
        Platinum: "প্লাটিনাম",
        Diamond: "ডায়মন্ড",
        Master: "মাস্টার",
        Grandmaster: "গ্র্যান্ডমাস্টার",
        Challenger: "চ্যালেঞ্জার",
        Legend: "লেজেন্ড",
        Mythical: "মিথিক্যাল"
    },
    id: {
        Unknown: "Tidak diketahui",
        Bronze: "Perunggu",
        Silver: "Perak",
        Gold: "Emas",
        Platinum: "Platinum",
        Diamond: "Berlian",
        Master: "Master",
        Grandmaster: "Grandmaster",
        Challenger: "Penantang",
        Legend: "Legenda",
        Mythical: "Mitis"
    }
}; 